format:
  docx:
    fig-format: png
    fig-dpi: 300
    df-print: paged
  pdf:
    documentclass: article
    keep-tex: true
    cite-method: biblatex
    include-in-header:
      - text: |
          \usepackage{multirow}

execute:
  echo: false
  warning: false
  error: false
